### ISSUE TITLE
Imported Datasets with KMS key blocks the environment stack update

### ISSUE THREAD

**Issue by ozggumus-aws** [data-dot-all/dataall#1024]
### Describe the bug

After we import an S3 bucket that is encrypted with a KMS key, we can't update the environment. I receive this error in the cdkproxy logs: 
`Failed to get kms key id of alias/SSE-S3: An error occurred (NotFoundException) 
when calling the DescribeKey operation: 
Alias arn:aws:kms:eu-central-1:AWSAccountNumber:alias/SSE-S3 is not found.`

Currently solved this issue by adding manual permissions to pivot role to describe key for SSE-S3.

### How to Reproduce

1) import a bucket with KMS key
2) try to update the environment stack

### OS

Win

### Python version

python3.9

### AWS data.all version

v2.2.0

**Comment by dlpzx** [comment]
Hi @ozggumus-aws, thanks for raising an issue. This issue looks a lot like an issue that was solved a couple of versions ago. Which version of the code are you running?

**Comment by ozggumus-aws** [comment]
@dlpzx It's v2.2, we still have this issue when a new s3 bucket is imported

**Comment by dlpzx** [comment]
We have been testing this issue and are not able to duplicate. Does the error persists?

**Comment by dlpzx** [comment]
We will close this item as it has been stale for a while. @ozggumus-aws If this issue persist, please let us know in this issue or in another new issue and we will work on it.
